"""drop fk constraints to auth.users

Revision ID: 1415103bb447
Revises: 4ebaee6990ba
Create Date: 2026-09-21 18:36:55.699854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1415103bb447'
down_revision: Union[str, Sequence[str], None] = '4ebaee6990ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitations_created_by_fkey'), 'invitations', type_='foreignkey')
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('rooms_created_by_fkey'), 'rooms', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('rooms_created_by_fkey'), 'rooms', 'users', ['created_by'], ['id'], referent_schema='auth')
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'], referent_schema='auth')
    op.create_foreign_key(op.f('invitations_created_by_fkey'), 'invitations', 'users', ['created_by'], ['id'], referent_schema='auth')
    # ### end Alembic commands ###
