"""link document images to posts

Revision ID: 9e29c43313a1
Revises: 2393196bb425
Create Date: 2026-09-21 23:08:19.983246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e29c43313a1'
down_revision: Union[str, Sequence[str], None] = '2393196bb425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable: existing images belong to the Document itself, not a Comment.
    op.add_column('document_images', sa.Column('post_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_document_images_post_id'), 'document_images', ['post_id'], unique=False)
    op.create_foreign_key('fk_document_images_post_id_posts', 'document_images', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_document_images_post_id_posts', 'document_images', type_='foreignkey')
    op.drop_index(op.f('ix_document_images_post_id'), table_name='document_images')
    op.drop_column('document_images', 'post_id')
    # ### end Alembic commands ###
